
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: npm i @venturemark/apigents
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - run: ls -R
